//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Parrot.Models
{
    public partial class CarList
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string Mobile_Consumer_ID
        {
            get;
            set;
        }
    
        public virtual string Mobile_ID
        {
            get;
            set;
        }
    
        public virtual int Mobile_Type
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sim
        {
            get;
            set;
        }
    
        public virtual string Mobile_SN
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Mobile_AddTag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Mobile_EditTag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> CanWebQuery
        {
            get;
            set;
        }
    
        public virtual string CreateDate
        {
            get;
            set;
        }
    
        public virtual string Attribute
        {
            get;
            set;
        }
    
        public virtual string UpStr
        {
            get;
            set;
        }
    
        public virtual string Mobile_VehicleRegistration
        {
            get;
            set;
        }
    
        public virtual string Users
        {
            get;
            set;
        }
    
        public virtual bool DelSign
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SysCreateDate
        {
            get;
            set;
        }
    
        public virtual int ClientID
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Sign
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsProbation
        {
            get;
            set;
        }
    
        public virtual string UptoDate
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsAuditing
        {
            get;
            set;
        }
    
        public virtual string Mobile_SimType
        {
            get;
            set;
        }
    
        public virtual string Mobile_UnitTypeName
        {
            get;
            set;
        }
    
        public virtual string NetParameter
        {
            get;
            set;
        }
    
        public virtual string SMSCenter1
        {
            get;
            set;
        }
    
        public virtual string SMSCenter2
        {
            get;
            set;
        }
    
        public virtual string DB44_EnterpriseCode
        {
            get;
            set;
        }
    
        public virtual string DB44_MDT_Type
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleRegistration_Type
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleType
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleUseType
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleGroupCode
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleGroupCYZGZ
        {
            get;
            set;
        }
    
        public virtual string DB44_CompanyCode
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleGroupName
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleRegistrationColor
        {
            get;
            set;
        }

        #endregion
    }
}
