//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Parrot.Models
{
    public partial class MobileInfoList
    {
        #region Primitive Properties
    
        public virtual string Mobile_Consumer_ID
        {
            get;
            set;
        }
    
        public virtual string Mobile_ID
        {
            get;
            set;
        }
    
        public virtual int Mobile_Type
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sim
        {
            get;
            set;
        }
    
        public virtual string Mobile_SN
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Mobile_AddTag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Mobile_EditTag
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Mobile_IntervalSms
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Mobile_IntervalUdp
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Mobile_IntervalTcp
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sensor_L2_L
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sensor_L2_H
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sensor_L1_L
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sensor_L1_H
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sensor_H2_L
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sensor_H2_H
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sensor_H1_L
        {
            get;
            set;
        }
    
        public virtual string Mobile_Sensor_H1_H
        {
            get;
            set;
        }
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual Nullable<float> Mobile_MostlyProtocol
        {
            get;
            set;
        }
    
        public virtual string Mobile_VehicleName
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> H1_H_Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> H1_L_Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> H2_H_Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> H2_L_Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> L1_H_Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> L1_L_Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> L2_H_Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> L2_L_Tag
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Power_Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> GPS_Tag
        {
            get;
            set;
        }
    
        public virtual string Mobile_VehicleRegistration
        {
            get;
            set;
        }
    
        public virtual string Attribute
        {
            get;
            set;
        }
    
        public virtual string NetParameter
        {
            get;
            set;
        }
    
        public virtual string SMSCenter2
        {
            get;
            set;
        }
    
        public virtual string SMSCenter1
        {
            get;
            set;
        }
    
        public virtual string Mobile_VehicleColor
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleGroupName
        {
            get;
            set;
        }
    
        public virtual string DB44_CompanyCode
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleRegistrationColor
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleGroupCYZGZ
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleGroupCode
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleUseType
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleType
        {
            get;
            set;
        }
    
        public virtual string DB44_VehicleRegistration_Type
        {
            get;
            set;
        }
    
        public virtual string DB44_MDT_Type
        {
            get;
            set;
        }
    
        public virtual string DB44_EnterpriseCode
        {
            get;
            set;
        }

        #endregion
    }
}
