//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Parrot.Models
{
    public partial class ParrotEntities : ObjectContext
    {
        public const string ConnectionString = "name=ParrotEntities";
        public const string ContainerName = "ParrotEntities";
    
        #region Constructors
    
        public ParrotEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ParrotEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ParrotEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<UserInfo> UserInfoes
        {
            get { return _userInfoes  ?? (_userInfoes = CreateObjectSet<UserInfo>("UserInfoes")); }
        }
        private ObjectSet<UserInfo> _userInfoes;
    
        public ObjectSet<UsrLogRec> UsrLogRecs
        {
            get { return _usrLogRecs  ?? (_usrLogRecs = CreateObjectSet<UsrLogRec>("UsrLogRecs")); }
        }
        private ObjectSet<UsrLogRec> _usrLogRecs;
    
        public ObjectSet<MobileInfoList> MobileInfoLists
        {
            get { return _mobileInfoLists  ?? (_mobileInfoLists = CreateObjectSet<MobileInfoList>("MobileInfoLists")); }
        }
        private ObjectSet<MobileInfoList> _mobileInfoLists;
    
        public ObjectSet<CarList> CarLists
        {
            get { return _carLists  ?? (_carLists = CreateObjectSet<CarList>("CarLists")); }
        }
        private ObjectSet<CarList> _carLists;

        #endregion
    }
}
