//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Parrot.Models
{
    public partial class UserInfo
    {
        #region Primitive Properties
    
        public virtual int User_Id
        {
            get;
            set;
        }
    
        public virtual string User_Name
        {
            get;
            set;
        }
    
        public virtual string User_Pwd
        {
            get;
            set;
        }
    
        public virtual Nullable<int> User_Type
        {
            get;
            set;
        }
    
        public virtual string User_WatchRangeType
        {
            get;
            set;
        }
    
        public virtual string User_RangerList
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> User_CreateTime
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> User_CanWebQuery
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsForbidden
        {
            get;
            set;
        }
    
        public virtual string Subjection
        {
            get;
            set;
        }
    
        public virtual string UIF_Version1
        {
            get;
            set;
        }
    
        public virtual string UIF_Version2
        {
            get;
            set;
        }
    
        public virtual string UIF_Version3
        {
            get;
            set;
        }
    
        public virtual string ClientName
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ClientID
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> AllowAuditing
        {
            get;
            set;
        }

        #endregion
    }
}
