//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Parrot.Models
{
    public partial class UsrLogRec
    {
        #region Primitive Properties
    
        public virtual int LogId
        {
            get;
            set;
        }
    
        public virtual string UsrName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LogOnTime
        {
            get;
            set;
        }
    
        public virtual string LogOffTime
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> LogResult
        {
            get;
            set;
        }
    
        public virtual string LogFrom
        {
            get;
            set;
        }

        #endregion
    }
}
